### ISSUE TITLE
Release hypercerts whitepaper

### ISSUE THREAD

**Issue by ccerv1** [Network-Goods/hypercerts#47]
https://docs.google.com/document/d/1456v3OWTnkQXQIo4lmud7b2qOXqsYwQo1EuN-GbsJU8/edit?usp=sharing

- [x] Structure whitepaper
- [x] Frist draft introduction
- [x] First draft of hypercert
- [x] First draft impact funding system
- [x] First draft open evaluation system
- [x] Revisit Impact Funding System
- [x] Structure incentive layer sections
- [x] First draft incentive layer section
- [x] First draft technical implementation @ryscheng 
- [ ] review of first draft
- [ ] implement suggestions from reviews
- [ ] review for grammar and clarity
- [ ] publish

**Comment by holkeb** [comment]
How much review do we want before we release the first draft?
- davidad review of content
- liam review for clarity
- legal review

How do we want to release the first draft?
- As a google doc or notion page in the hypercert TG asking for comments
- As markdown in github

**Comment by ryscheng** [comment]
I want to balance working in the public with the fact that if we can convince someone to read the whitepaper, the vast majority of people will read it at most one time.

So the way I'd look at it is, what is the sharing order that would maximize highest velocity to improving the whitepaper's quality of writing? If there are specific individuals who can provide quality feedback for an iteration, we should focus on that first IMO.

**Comment by holkeb** [comment]
Sounds right to me. So, in addition to the reviews I suggested above, we can add a small group of external reviewers to give us comments. Have that iteration and then release to the TG group and everyone else at the same time

**Comment by holkeb** [comment]
@ryscheng feel free to add anything to the section on the technical implementation. You can change the structure of that section completely. The titles are only very quick suggestions. 

We can also keep the technical documentation separate from the whitepaper if it doesn't fully fit. I think the audience of that section would be projects like Molecule, LabDAO and all the others that presented at the first community call who might want to use hypercerts themselves or be compatible with them. If you write it with them in mind, we can choose later if it should be part of the whitepaper or a separate document.

Let me know if you need any additional information from me.

And for the general timeline. I would love to have a public version whenever we go public with the first pilot. That way we can direct any further interest to the whitepaper.

**Comment by holkeb** [comment]
I'm still not happy with all parts of the whitepaper draft, but I think it is ready for review: https://docs.google.com/document/d/1456v3OWTnkQXQIo4lmud7b2qOXqsYwQo1EuN-GbsJU8/edit?usp=sharing

If you have time to review it, your thoughts and comments are much appreciated. Feel free to take apart anything you like (= what you don't like), I will ignore comments that I don't like ;) Also feel free to make suggestions directly in text.

If you have reviewed it, feel free to mark it here (the list doesn't mean you have to review it):
- [ ] davidad 
- [ ] @miyazono 
- [ ] @MF416  (esp. impact evaluator sections)
- [ ] @wheresaddie 
- [ ] @coreymjames 
- [ ] @KarolaKirsanow 
- [ ] @silvianetobessa 
- [ ] @ccerv1 
- [ ] @ryscheng 

@KarolaKirsanow and @silvianetobessa: the brief section on roadmapping has much more potential I believe and I would also love to cite some of our/your work if you have a suggestion for that

Regarding grammar and clarity, @liam-ohagan will review it before it will be published (you are welcome to suggest those changes as well of course – as you like)

**Comment by wheresaddie** [comment]
marking myself as 'read' as I will be done later today

**Comment by ccerv1** [comment]
@holkeb FYI, I'm going to close this out since the whitepaper has been released and is [linked in the docs](https://hypercerts.vercel.app/docs/assets/files/hypercerts_whitepaper_v0-de6931aa09ed24c8e5280e264c85af23.pdf). We can open additional issues for versioning or other edits.
